### ISSUE TITLE
[Error] - VirtualPack fails to load with bukkit 1.8.3

### ISSUE THREAD

**Issue by mibby** [Siguza/VirtualPack#27]
Spigot 1.8.3 has been released. VirtualPack fails to load.
```
[13:51:09] [Server thread/INFO]: [VirtualPack] Enabling VirtualPack v2.7.8
[13:51:09] [Server thread/ERROR]: Error occurred while enabling VirtualPack v2.7.8 (Is it up to date?)
java.lang.NoClassDefFoundError: net/minecraft/server/v1_8_R1/IChatBaseComponent
	at net.drgnome.virtualpack.util.ConfigProxy.setDefs(ConfigProxy.java:137) ~[?:?]
	at net.drgnome.virtualpack.util.ConfigProxy.<init>(ConfigProxy.java:91) ~[?:?]
	at net.drgnome.virtualpack.util.Config.reload(Config.java:27) ~[?:?]
	at net.drgnome.virtualpack.VPlugin.reloadConfig(VPlugin.java:896) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.getConfig(JavaPlugin.java:162) ~[spigot-1.8.3.jar:git-Spigot-fcb68de-1e56438]
	at net.drgnome.virtualpack.util.Config.reload(Config.java:27) ~[?:?]
	at net.drgnome.virtualpack.VPlugin.init(VPlugin.java:85) ~[?:?]
	at net.drgnome.virtualpack.VPlugin.onEnable(VPlugin.java:256) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot-1.8.3.jar:git-Spigot-fcb68de-1e56438]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) [spigot-1.8.3.jar:git-Spigot-fcb68de-1e56438]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.8.3.jar:git-Spigot-fcb68de-1e56438]
	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.loadPlugin(CraftServer.java:356) [spigot-1.8.3.jar:git-Spigot-fcb68de-1e56438]
	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.enablePlugins(CraftServer.java:316) [spigot-1.8.3.jar:git-Spigot-fcb68de-1e56438]
	at net.minecraft.server.v1_8_R2.MinecraftServer.r(MinecraftServer.java:420) [spigot-1.8.3.jar:git-Spigot-fcb68de-1e56438]
	at net.minecraft.server.v1_8_R2.MinecraftServer.k(MinecraftServer.java:386) [spigot-1.8.3.jar:git-Spigot-fcb68de-1e56438]
	at net.minecraft.server.v1_8_R2.MinecraftServer.a(MinecraftServer.java:341) [spigot-1.8.3.jar:git-Spigot-fcb68de-1e56438]
	at net.minecraft.server.v1_8_R2.DedicatedServer.init(DedicatedServer.java:257) [spigot-1.8.3.jar:git-Spigot-fcb68de-1e56438]
	at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:526) [spigot-1.8.3.jar:git-Spigot-fcb68de-1e56438]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_40]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_8_R1.IChatBaseComponent
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[spigot-1.8.3.jar:git-Spigot-fcb68de-1e56438]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.8.3.jar:git-Spigot-fcb68de-1e56438]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_40]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_40]
	... 19 more
```

**Comment by Siguza** [comment]
Closed with bb1e3269332f49cc8157c57a4f389bef04afd382.
