### ISSUE TITLE
1.10 Support - NoClassDefFoundError

### ISSUE THREAD

**Issue by mibby** [Siguza/VirtualPack#38]
```
[01:19:16] [Server thread/INFO]: [VirtualPack] Enabling VirtualPack v2.8.6
[01:19:16] [Server thread/ERROR]: Error occurred while enabling VirtualPack v2.8.6 (Is it up to date?)
java.lang.NoClassDefFoundError: net/minecraft/server/v1_9_R2/IChatBaseComponent
	at net.drgnome.virtualpack.util.ConfigProxy.setDefs(ConfigProxy.java:137) ~[?:?]
	at net.drgnome.virtualpack.util.ConfigProxy.<init>(ConfigProxy.java:91) ~[?:?]
	at net.drgnome.virtualpack.util.Config.reload(Config.java:27) ~[?:?]
	at net.drgnome.virtualpack.VPlugin.reloadConfig(VPlugin.java:906) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.getConfig(JavaPlugin.java:163) ~[patched_1.10.jar:git-Paper-775]
	at net.drgnome.virtualpack.util.Config.reload(Config.java:27) ~[?:?]
	at net.drgnome.virtualpack.VPlugin.init(VPlugin.java:87) ~[?:?]
	at net.drgnome.virtualpack.VPlugin.onEnable(VPlugin.java:265) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[patched_1.10.jar:git-Paper-775]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:319) [patched_1.10.jar:git-Paper-775]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched_1.10.jar:git-Paper-775]
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugin(CraftServer.java:358) [patched_1.10.jar:git-Paper-775]
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:318) [patched_1.10.jar:git-Paper-775]
	at net.minecraft.server.v1_10_R1.MinecraftServer.t(MinecraftServer.java:414) [patched_1.10.jar:git-Paper-775]
	at net.minecraft.server.v1_10_R1.MinecraftServer.l(MinecraftServer.java:379) [patched_1.10.jar:git-Paper-775]
	at net.minecraft.server.v1_10_R1.MinecraftServer.a(MinecraftServer.java:333) [patched_1.10.jar:git-Paper-775]
	at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:274) [patched_1.10.jar:git-Paper-775]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:580) [patched_1.10.jar:git-Paper-775]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_92]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_9_R2.IChatBaseComponent
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:92) ~[patched_1.10.jar:git-Paper-775]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[patched_1.10.jar:git-Paper-775]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_92]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_92]
	... 19 more
[01:19:16] [Server thread/INFO]: [VirtualPack] Disabling VirtualPack v2.8.6
[01:19:16] [Server thread/ERROR]: Error occurred while disabling VirtualPack v2.8.6 (Is it up to date?)
java.lang.NullPointerException
	at net.drgnome.virtualpack.util.Config.string(Config.java:72) ~[?:?]
	at net.drgnome.virtualpack.util.Config.bool(Config.java:85) ~[?:?]
	at net.drgnome.virtualpack.util.Config.bool(Config.java:80) ~[?:?]
	at net.drgnome.virtualpack.VPlugin.onDisable(VPlugin.java:279) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:294) ~[patched_1.10.jar:git-Paper-775]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:347) [patched_1.10.jar:git-Paper-775]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:323) [patched_1.10.jar:git-Paper-775]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched_1.10.jar:git-Paper-775]
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugin(CraftServer.java:358) [patched_1.10.jar:git-Paper-775]
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:318) [patched_1.10.jar:git-Paper-775]
	at net.minecraft.server.v1_10_R1.MinecraftServer.t(MinecraftServer.java:414) [patched_1.10.jar:git-Paper-775]
	at net.minecraft.server.v1_10_R1.MinecraftServer.l(MinecraftServer.java:379) [patched_1.10.jar:git-Paper-775]
	at net.minecraft.server.v1_10_R1.MinecraftServer.a(MinecraftServer.java:333) [patched_1.10.jar:git-Paper-775]
	at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:274) [patched_1.10.jar:git-Paper-775]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:580) [patched_1.10.jar:git-Paper-775]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_92]
```

**Comment by Siguza** [comment]
fe973bde3fca26236ca93a0a35413aeb741ad8f3 should fix.

**Comment by mibby** [comment]
Thanks. :)
