### ISSUE TITLE
NullPointerException: null on server stop with semi-loading, prior to being loaded in full.

### ISSUE THREAD

**Issue by mibby** [Siguza/VirtualPack#46]
```
[02:54:34] [Server thread/INFO]: [VirtualPack] Disabling VirtualPack v2.8.13
[02:54:34] [Server thread/WARN]: [VirtualPack] CANNOT SAVE USER DATA, LOADING ALREADY FAILED!
[02:54:34] [Server thread/ERROR]: Error occurred while disabling VirtualPack v2.8.13 (Is it up to date?)
java.lang.NullPointerException: null
	at net.drgnome.virtualpack.VPlugin.onDisable(VPlugin.java:307) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[patched_1.12.2.jar:git-Paper-1220]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:344) [patched_1.12.2.jar:git-Paper-1220]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:424) [patched_1.12.2.jar:git-Paper-1220]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:417) [patched_1.12.2.jar:git-Paper-1220]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.disablePlugins(CraftServer.java:354) [patched_1.12.2.jar:git-Paper-1220]
	at net.minecraft.server.v1_12_R1.MinecraftServer.stop(MinecraftServer.java:486) [patched_1.12.2.jar:git-Paper-1220]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:701) [patched_1.12.2.jar:git-Paper-1220]
	at java.lang.Thread.run(Thread.java:844) [?:?]
```

**Comment by Siguza** [comment]
Should be fixed with 5721c72a09e50a08493a1c1236fec825a7a663bb (otherwise, please reopen/comment further).
