### ISSUE TITLE
Java 9 support.

### ISSUE THREAD

**Issue by mibby** [Siguza/VirtualPack#47]
```
[02:54:22] [Thread-15/WARN]: Exception in thread "Thread-15" java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
[02:54:22] [Thread-15/WARN]:     at net.drgnome.virtualpack.util.Util.stringToItemStack(Util.java:364)
[02:54:22] [Thread-15/WARN]:     at net.drgnome.virtualpack.components.VTEFurnace.<init>(VTEFurnace.java:56)
[02:54:22] [Thread-15/WARN]:     at net.drgnome.virtualpack.VPack.init(VPack.java:140)
[02:54:22] [Thread-15/WARN]:     at net.drgnome.virtualpack.VPack.<init>(VPack.java:80)
[02:54:22] [Thread-15/WARN]:     at net.drgnome.virtualpack.VPlugin.load(VPlugin.java:869)
[02:54:22] [Thread-15/WARN]:     at net.drgnome.virtualpack.VPlugin.loadFlatfile(VPlugin.java:809)
[02:54:22] [Thread-15/WARN]:     at net.drgnome.virtualpack.VPlugin.loadUserData0(VPlugin.java:724)
[02:54:22] [Thread-15/WARN]:     at net.drgnome.virtualpack.thread.VThreadInit.run(VThreadInit.java:13)
[02:54:22] [Thread-15/WARN]: Caused by: java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter
[02:54:22] [Thread-15/WARN]:     at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:466)
[02:54:22] [Thread-15/WARN]:     at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104)
[02:54:22] [Thread-15/WARN]:     at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:89)
[02:54:22] [Thread-15/WARN]:     at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:563)
[02:54:22] [Thread-15/WARN]:     at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
[02:54:22] [Thread-15/WARN]:     ... 8 more
```

**Comment by mibby** [comment]
@Siguza Any update to this issue for java 9 support? :(

**Comment by Siguza** [comment]
Had a look at it, but not sure how to handle it. I'll either have to drop Java 6 and 7 support, or fall back to ugly/slow workarounds.

**Comment by mibby** [comment]
Java 7 went EOL around April 2015 if I recall correctly, so I'd just move on with supporting Java 8 & 9 for future releases personally. I doubt many servers still run on Java 6 or 7.

**Comment by Siguza** [comment]
Fair enough. Commits 3a7597c161b67e90501129a7e47c2a065f91b9c8 / ca71a4ef803554480039f04a03bf4a3c30aaebc3 make the needed changes.
