### ISSUE TITLE
1.13 support.

### ISSUE THREAD

**Issue by mibby** [Siguza/VirtualPack#49]
Spigot 1.13 pre-release builds have been released. Might want to prepare for 1.13 breaking changes? :)
https://www.spigotmc.org/threads/bukkit-craftbukkit-spigot-bungeecord-1-13-pre7-development-builds.328883/

**Comment by mibby** [comment]
Sure, no problem. :)

**Comment by mibby** [comment]
1.13 has officially been released now.

**Comment by mibby** [comment]
I've been testing out a bunch of plugins in a new 1.13 environment to see what breaks. Just thought I'd let you know about this error for when you update to 1.13. :)

VirtualPack compiled as of commit https://github.com/Siguza/VirtualPack/commit/8ab2619e5db175856571c825825d085a15a12d6a
Paper-1.13 dev 152 (Spigot 1.13)

```
[13:07:57] [Server thread/INFO]: [VirtualPack] Enabling VirtualPack v2.8.14*
[13:07:57] [Server thread/ERROR]: Error occurred while enabling VirtualPack v2.8.14 (Is it up to date?)
java.lang.NoClassDefFoundError: net/minecraft/server/v1_12_R1/IChatBaseComponent
	at net.drgnome.virtualpack.util.ConfigProxy.setDefs(ConfigProxy.java:138) ~[?:?]
	at net.drgnome.virtualpack.util.ConfigProxy.<init>(ConfigProxy.java:91) ~[?:?]
	at net.drgnome.virtualpack.util.Config.reload(Config.java:27) ~[?:?]
	at net.drgnome.virtualpack.VPlugin.reloadConfig(VPlugin.java:908) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.getConfig(JavaPlugin.java:135) ~[patched_1.13.jar:git-Paper-152]
	at net.drgnome.virtualpack.util.Config.reload(Config.java:27) ~[?:?]
	at net.drgnome.virtualpack.VPlugin.init(VPlugin.java:87) ~[?:?]
	at net.drgnome.virtualpack.VPlugin.onEnable(VPlugin.java:264) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.13.jar:git-Paper-152]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:325) ~[patched_1.13.jar:git-Paper-152]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.13.jar:git-Paper-152]
	at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugin(CraftServer.java:433) ~[patched_1.13.jar:git-Paper-152]
	at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugins(CraftServer.java:347) ~[patched_1.13.jar:git-Paper-152]
	at net.minecraft.server.v1_13_R1.MinecraftServer.m(MinecraftServer.java:589) ~[patched_1.13.jar:git-Paper-152]
	at net.minecraft.server.v1_13_R1.MinecraftServer.g_(MinecraftServer.java:551) ~[patched_1.13.jar:git-Paper-152]
	at net.minecraft.server.v1_13_R1.MinecraftServer.a(MinecraftServer.java:428) ~[patched_1.13.jar:git-Paper-152]
	at net.minecraft.server.v1_13_R1.DedicatedServer.init(DedicatedServer.java:305) ~[patched_1.13.jar:git-Paper-152]
	at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:764) ~[patched_1.13.jar:git-Paper-152]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_12_R1.IChatBaseComponent
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:109) ~[patched_1.13.jar:git-Paper-152]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104) ~[patched_1.13.jar:git-Paper-152]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_181]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_181]
	... 19 more
[13:07:57] [Server thread/INFO]: [VirtualPack] Disabling VirtualPack v2.8.14
[13:07:57] [Server thread/ERROR]: Error occurred while disabling VirtualPack v2.8.14 (Is it up to date?)
java.lang.NullPointerException: null
	at net.drgnome.virtualpack.util.Config.string(Config.java:72) ~[?:?]
	at net.drgnome.virtualpack.util.Config.bool(Config.java:85) ~[?:?]
	at net.drgnome.virtualpack.util.Config.bool(Config.java:80) ~[?:?]
	at net.drgnome.virtualpack.VPlugin.onDisable(VPlugin.java:278) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[patched_1.13.jar:git-Paper-152]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:359) ~[patched_1.13.jar:git-Paper-152]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:329) ~[patched_1.13.jar:git-Paper-152]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.13.jar:git-Paper-152]
	at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugin(CraftServer.java:433) ~[patched_1.13.jar:git-Paper-152]
	at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugins(CraftServer.java:347) ~[patched_1.13.jar:git-Paper-152]
	at net.minecraft.server.v1_13_R1.MinecraftServer.m(MinecraftServer.java:589) ~[patched_1.13.jar:git-Paper-152]
	at net.minecraft.server.v1_13_R1.MinecraftServer.g_(MinecraftServer.java:551) ~[patched_1.13.jar:git-Paper-152]
	at net.minecraft.server.v1_13_R1.MinecraftServer.a(MinecraftServer.java:428) ~[patched_1.13.jar:git-Paper-152]
	at net.minecraft.server.v1_13_R1.DedicatedServer.init(DedicatedServer.java:305) ~[patched_1.13.jar:git-Paper-152]
	at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:764) ~[patched_1.13.jar:git-Paper-152]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
```

**Comment by mibby** [comment]
Happy September! :)

**Comment by mibby** [comment]
@Siguza Any possible update on 1.13 support?

**Comment by jordanwilliams1** [comment]
@Siguza I Wouldn't blame you for not updating this, But is there any possible chance you could give it one last update?

**Comment by mibby** [comment]
@Siguza It's October now. :(

**Comment by Siguza** [comment]
Working on it, just taking way longer than anticipated. They removed item and block IDs. Completely. It's just names now. This is hell.

**Comment by Siguza** [comment]
Just pushed my changes - it compiles against 1.13 now, but I haven't had the chance to test anything.
Anything may or may not work. Feel free to test stuff, but do not use on production.

**Comment by Siguza** [comment]
Ok, with the latest commit both 1.13 and 1.13.1 should be pretty much working. I'd be really grateful if you could test whether everything works as expected on your setup(s) too.

**Comment by mibby** [comment]
Thank you very much for updating! I'll compile right away and give it a test. I'll let you know if I come across any issues.

**Comment by Siguza** [comment]
Alright, as far as I'm able to tell, everything works as it should.  
I pushed a build for 1.13.1 at Bukkit (pending approval as of right now) and for all versions at [ci.siguza.net](https://ci.siguza.net).

I consider this ticket as resolved now, please file a bug report for any future issues you encounter.  
Otherwise, see y'all on the next Minecraft update.
