### ISSUE TITLE
COULD NOT LOAD USER DATA! - ConcurrentModificationException

### ISSUE THREAD

**Issue by mibby** [Siguza/VirtualPack#51]
VirtualPack compiled as of commit 
https://github.com/Siguza/VirtualPack/commit/cf00f4a21e912a89794e344e4eec3d1ca7ebb248
Paper dev 444 (Spigot 1.13.2)

@Siguza 
```
[13:33:06] [Thread-29/ERROR]: [VirtualPack] COULD NOT LOAD USER DATA!
[13:33:06] [Thread-29/WARN]: java.util.ConcurrentModificationException
[13:33:06] [Thread-29/WARN]: 	at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1493)
[13:33:06] [Thread-29/WARN]: 	at java.base/java.util.HashMap$ValueIterator.next(HashMap.java:1521)
[13:33:06] [Thread-29/WARN]: 	at net.minecraft.server.v1_13_R2.CraftingManager.b(CraftingManager.java:122)
[13:33:06] [Thread-29/WARN]: 	at net.drgnome.virtualpack.components.VTEFurnace.getRecipe(VTEFurnace.java:578)
[13:33:06] [Thread-29/WARN]: 	at net.drgnome.virtualpack.components.VTEFurnace.proxyGetBurnTime(VTEFurnace.java:572)
[13:33:06] [Thread-29/WARN]: 	at net.drgnome.virtualpack.components.VTEFurnace.<init>(VTEFurnace.java:103)
[13:33:06] [Thread-29/WARN]: 	at net.drgnome.virtualpack.VPack.init(VPack.java:140)
[13:33:06] [Thread-29/WARN]: 	at net.drgnome.virtualpack.VPack.<init>(VPack.java:80)
[13:33:06] [Thread-29/WARN]: 	at net.drgnome.virtualpack.VPlugin.load(VPlugin.java:872)
[13:33:06] [Thread-29/WARN]: 	at net.drgnome.virtualpack.VPlugin.loadFlatfile(VPlugin.java:812)
[13:33:06] [Thread-29/WARN]: 	at net.drgnome.virtualpack.VPlugin.loadUserData0(VPlugin.java:727)
[13:33:06] [Thread-29/WARN]: 	at net.drgnome.virtualpack.thread.VThreadInit.run(VThreadInit.java:13)
```

**Comment by Siguza** [comment]
Hmm, can't reproduce.  
Could you give me a list of plugins you use? Are there any which add crafting/cooking recipes?

**Comment by mibby** [comment]
@Siguza Apologies, I'm back from the dead now. I think it may have been an issue with someone having an invalid item in their furnace or something. I just purged the data.db file.
