### ISSUE TITLE
NoSuchMethodError: net.minecraft.server.v1_13_R2.World.E()Lnet/minecraft/server/v1_13_R2/CraftingManager

### ISSUE THREAD

**Issue by mibby** [Siguza/VirtualPack#52]
Paper dev 488 (Spigot 1.13.2)
VirtualPack v2.8.15 https://github.com/Siguza/VirtualPack/commit/cf00f4a21e912a89794e344e4eec3d1ca7ebb248

@Siguza :(
```
[04:41:18] [Server thread/INFO]: VirtualPack 2.8.15 enabled
[04:41:18] [Thread-27/WARN]: Exception in thread "Thread-27" java.lang.NoSuchMethodError: net.minecraft.server.v1_13_R2.World.E()Lnet/minecraft/server/v1_13_R2/CraftingManager;
[04:41:18] [Thread-27/WARN]: 	at net.drgnome.virtualpack.components.VTEFurnace.getRecipe(VTEFurnace.java:578)
[04:41:18] [Thread-27/WARN]: 	at net.drgnome.virtualpack.components.VTEFurnace.proxyGetBurnTime(VTEFurnace.java:572)
[04:41:18] [Thread-27/WARN]: 	at net.drgnome.virtualpack.components.VTEFurnace.<init>(VTEFurnace.java:103)
[04:41:18] [Thread-27/WARN]: 	at net.drgnome.virtualpack.VPack.init(VPack.java:140)
[04:41:18] [Thread-27/WARN]: 	at net.drgnome.virtualpack.VPack.<init>(VPack.java:80)
[04:41:18] [Thread-27/WARN]: 	at net.drgnome.virtualpack.VPlugin.load(VPlugin.java:872)
[04:41:18] [Thread-27/WARN]: 	at net.drgnome.virtualpack.VPlugin.loadFlatfile(VPlugin.java:812)
[04:41:18] [Thread-27/WARN]: 	at net.drgnome.virtualpack.VPlugin.loadUserData0(VPlugin.java:727)
[04:41:18] [Thread-27/WARN]: 	at net.drgnome.virtualpack.thread.VThreadInit.run(VThreadInit.java:13)
```

**Comment by mibby** [comment]
```
[09:12:27] [Server thread/WARN]: [VirtualPack] Task #116 for VirtualPack v2.8.15 generated an exception
java.lang.NoSuchMethodError: net.minecraft.server.v1_13_R2.World.E()Lnet/minecraft/server/v1_13_R2/CraftingManager;
	at net.drgnome.virtualpack.components.VTEFurnace.getRecipe(VTEFurnace.java:578) ~[?:?]
	at net.drgnome.virtualpack.components.VTEFurnace.getBurnResult(VTEFurnace.java:336) ~[?:?]
	at net.drgnome.virtualpack.components.VTEFurnace.canHasBURN(VTEFurnace.java:387) ~[?:?]
	at net.drgnome.virtualpack.components.VTEFurnace.isFine(VTEFurnace.java:316) ~[?:?]
	at net.drgnome.virtualpack.components.VTEFurnace.checkLink(VTEFurnace.java:194) ~[?:?]
	at net.drgnome.virtualpack.components.VTEFurnace.tick(VTEFurnace.java:124) ~[?:?]
	at net.drgnome.virtualpack.VPack.tick(VPack.java:238) ~[?:?]
	at net.drgnome.virtualpack.VPlugin.run(VPlugin.java:1061) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[patched_1.13.2.jar:git-Paper-488]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:448) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1008) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.2.jar:git-Paper-488]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[09:12:28] [Server thread/WARN]: [VirtualPack] Task #116 for VirtualPack v2.8.15 generated an exception
java.lang.NoSuchMethodError: net.minecraft.server.v1_13_R2.World.E()Lnet/minecraft/server/v1_13_R2/CraftingManager;
	at net.drgnome.virtualpack.components.VTEFurnace.getRecipe(VTEFurnace.java:578) ~[?:?]
	at net.drgnome.virtualpack.components.VTEFurnace.getBurnResult(VTEFurnace.java:336) ~[?:?]
	at net.drgnome.virtualpack.components.VTEFurnace.canHasBURN(VTEFurnace.java:387) ~[?:?]
	at net.drgnome.virtualpack.components.VTEFurnace.isFine(VTEFurnace.java:316) ~[?:?]
	at net.drgnome.virtualpack.components.VTEFurnace.checkLink(VTEFurnace.java:194) ~[?:?]
	at net.drgnome.virtualpack.components.VTEFurnace.tick(VTEFurnace.java:124) ~[?:?]
	at net.drgnome.virtualpack.VPack.tick(VPack.java:238) ~[?:?]
	at net.drgnome.virtualpack.VPlugin.run(VPlugin.java:1061) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[patched_1.13.2.jar:git-Paper-488]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:448) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1008) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.2.jar:git-Paper-488]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[09:12:30] [Server thread/WARN]: [VirtualPack] Task #116 for VirtualPack v2.8.15 generated an exception
java.lang.NoSuchMethodError: net.minecraft.server.v1_13_R2.World.E()Lnet/minecraft/server/v1_13_R2/CraftingManager;
	at net.drgnome.virtualpack.components.VTEFurnace.getRecipe(VTEFurnace.java:578) ~[?:?]
	at net.drgnome.virtualpack.components.VTEFurnace.getBurnResult(VTEFurnace.java:336) ~[?:?]
	at net.drgnome.virtualpack.components.VTEFurnace.canHasBURN(VTEFurnace.java:387) ~[?:?]
	at net.drgnome.virtualpack.components.VTEFurnace.isFine(VTEFurnace.java:316) ~[?:?]
	at net.drgnome.virtualpack.components.VTEFurnace.checkLink(VTEFurnace.java:194) ~[?:?]
	at net.drgnome.virtualpack.components.VTEFurnace.tick(VTEFurnace.java:124) ~[?:?]
	at net.drgnome.virtualpack.VPack.tick(VPack.java:238) ~[?:?]
	at net.drgnome.virtualpack.VPlugin.run(VPlugin.java:1061) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[patched_1.13.2.jar:git-Paper-488]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:448) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1008) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.2.jar:git-Paper-488]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[09:12:31] [Server thread/WARN]: [VirtualPack] Task #116 for VirtualPack v2.8.15 generated an exception
java.lang.NoSuchMethodError: net.minecraft.server.v1_13_R2.World.E()Lnet/minecraft/server/v1_13_R2/CraftingManager;
	at net.drgnome.virtualpack.components.VTEFurnace.getRecipe(VTEFurnace.java:578) ~[?:?]
	at net.drgnome.virtualpack.components.VTEFurnace.getBurnResult(VTEFurnace.java:336) ~[?:?]
	at net.drgnome.virtualpack.components.VTEFurnace.canHasBURN(VTEFurnace.java:387) ~[?:?]
	at net.drgnome.virtualpack.components.VTEFurnace.isFine(VTEFurnace.java:316) ~[?:?]
	at net.drgnome.virtualpack.components.VTEFurnace.checkLink(VTEFurnace.java:194) ~[?:?]
	at net.drgnome.virtualpack.components.VTEFurnace.tick(VTEFurnace.java:124) ~[?:?]
	at net.drgnome.virtualpack.VPack.tick(VPack.java:238) ~[?:?]
	at net.drgnome.virtualpack.VPlugin.run(VPlugin.java:1061) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[patched_1.13.2.jar:git-Paper-488]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:448) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1008) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.2.jar:git-Paper-488]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[09:12:33] [Server thread/WARN]: [VirtualPack] Task #116 for VirtualPack v2.8.15 generated an exception
java.lang.NoSuchMethodError: net.minecraft.server.v1_13_R2.World.E()Lnet/minecraft/server/v1_13_R2/CraftingManager;
	at net.drgnome.virtualpack.components.VTEFurnace.getRecipe(VTEFurnace.java:578) ~[?:?]
	at net.drgnome.virtualpack.components.VTEFurnace.getBurnResult(VTEFurnace.java:336) ~[?:?]
	at net.drgnome.virtualpack.components.VTEFurnace.canHasBURN(VTEFurnace.java:387) ~[?:?]
	at net.drgnome.virtualpack.components.VTEFurnace.isFine(VTEFurnace.java:316) ~[?:?]
	at net.drgnome.virtualpack.components.VTEFurnace.checkLink(VTEFurnace.java:194) ~[?:?]
	at net.drgnome.virtualpack.components.VTEFurnace.tick(VTEFurnace.java:124) ~[?:?]
	at net.drgnome.virtualpack.VPack.tick(VPack.java:238) ~[?:?]
	at net.drgnome.virtualpack.VPlugin.run(VPlugin.java:1061) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[patched_1.13.2.jar:git-Paper-488]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:448) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1008) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.2.jar:git-Paper-488]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[09:12:34] [Server thread/WARN]: [VirtualPack] Task #116 for VirtualPack v2.8.15 generated an exception
java.lang.NoSuchMethodError: net.minecraft.server.v1_13_R2.World.E()Lnet/minecraft/server/v1_13_R2/CraftingManager;
	at net.drgnome.virtualpack.components.VTEFurnace.getRecipe(VTEFurnace.java:578) ~[?:?]
	at net.drgnome.virtualpack.components.VTEFurnace.getBurnResult(VTEFurnace.java:336) ~[?:?]
	at net.drgnome.virtualpack.components.VTEFurnace.canHasBURN(VTEFurnace.java:387) ~[?:?]
	at net.drgnome.virtualpack.components.VTEFurnace.isFine(VTEFurnace.java:316) ~[?:?]
	at net.drgnome.virtualpack.components.VTEFurnace.checkLink(VTEFurnace.java:194) ~[?:?]
	at net.drgnome.virtualpack.components.VTEFurnace.tick(VTEFurnace.java:124) ~[?:?]
	at net.drgnome.virtualpack.VPack.tick(VPack.java:238) ~[?:?]
	at net.drgnome.virtualpack.VPlugin.run(VPlugin.java:1061) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[patched_1.13.2.jar:git-Paper-488]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:448) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1008) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.2.jar:git-Paper-488]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[09:12:36] [Server thread/WARN]: [VirtualPack] Task #116 for VirtualPack v2.8.15 generated an exception
java.lang.NoSuchMethodError: net.minecraft.server.v1_13_R2.World.E()Lnet/minecraft/server/v1_13_R2/CraftingManager;
	at net.drgnome.virtualpack.components.VTEFurnace.getRecipe(VTEFurnace.java:578) ~[?:?]
	at net.drgnome.virtualpack.components.VTEFurnace.getBurnResult(VTEFurnace.java:336) ~[?:?]
	at net.drgnome.virtualpack.components.VTEFurnace.canHasBURN(VTEFurnace.java:387) ~[?:?]
	at net.drgnome.virtualpack.components.VTEFurnace.isFine(VTEFurnace.java:316) ~[?:?]
	at net.drgnome.virtualpack.components.VTEFurnace.checkLink(VTEFurnace.java:194) ~[?:?]
	at net.drgnome.virtualpack.components.VTEFurnace.tick(VTEFurnace.java:124) ~[?:?]
	at net.drgnome.virtualpack.VPack.tick(VPack.java:238) ~[?:?]
	at net.drgnome.virtualpack.VPlugin.run(VPlugin.java:1061) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[patched_1.13.2.jar:git-Paper-488]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:448) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1008) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.2.jar:git-Paper-488]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[09:12:37] [Server thread/WARN]: [VirtualPack] Task #116 for VirtualPack v2.8.15 generated an exception
java.lang.NoSuchMethodError: net.minecraft.server.v1_13_R2.World.E()Lnet/minecraft/server/v1_13_R2/CraftingManager;
	at net.drgnome.virtualpack.components.VTEFurnace.getRecipe(VTEFurnace.java:578) ~[?:?]
	at net.drgnome.virtualpack.components.VTEFurnace.getBurnResult(VTEFurnace.java:336) ~[?:?]
	at net.drgnome.virtualpack.components.VTEFurnace.canHasBURN(VTEFurnace.java:387) ~[?:?]
	at net.drgnome.virtualpack.components.VTEFurnace.isFine(VTEFurnace.java:316) ~[?:?]
	at net.drgnome.virtualpack.components.VTEFurnace.checkLink(VTEFurnace.java:194) ~[?:?]
	at net.drgnome.virtualpack.components.VTEFurnace.tick(VTEFurnace.java:124) ~[?:?]
	at net.drgnome.virtualpack.VPack.tick(VPack.java:238) ~[?:?]
	at net.drgnome.virtualpack.VPlugin.run(VPlugin.java:1061) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[patched_1.13.2.jar:git-Paper-488]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:448) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1008) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.2.jar:git-Paper-488]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

Which led into this being spammed thousands of times a second until crashing the server. Log file blew up in size really quickly too.

```
[09:13:16] [Server thread/ERROR]: Can't find any space for item in the inventory
[09:13:16] [Server thread/ERROR]: Can't find any space for item in the inventory
[09:13:16] [Server thread/ERROR]: Can't find any space for item in the inventory
[09:13:16] [Server thread/ERROR]: Can't find any space for item in the inventory
[09:13:16] [Server thread/ERROR]: Can't find any space for item in the inventory
[09:13:16] [Server thread/ERROR]: Can't find any space for item in the inventory
[09:13:16] [Server thread/ERROR]: Can't find any space for item in the inventory
[09:13:16] [Server thread/ERROR]: Can't find any space for item in the inventory
[09:13:16] [Server thread/ERROR]: Can't find any space for item in the inventory
[09:13:16] [Server thread/ERROR]: Can't find any space for item in the inventory
[09:13:16] [Server thread/ERROR]: Can't find any space for item in the inventory
[09:13:16] [Server thread/ERROR]: Can't find any space for item in the inventory
[09:13:16] [Server thread/ERROR]: Can't find any space for item in the inventory
[09:13:16] [Server thread/ERROR]: Can't find any space for item in the inventory
[09:13:16] [Server thread/ERROR]: Can't find any space for item in the inventory
[09:13:16] [Server thread/ERROR]: Can't find any space for item in the inventory
[09:13:16] [Server thread/ERROR]: Can't find any space for item in the inventory
[09:13:16] [Server thread/ERROR]: Can't find any space for item in the inventory
[09:13:16] [Server thread/ERROR]: Can't find any space for item in the inventory
```

**Comment by mibby** [comment]
@Siguza Please fix when you get the chance. There's nothing quite like VirtualPack and this error is breaking enough to force me to remove it. :(

**Comment by mibby** [comment]
@Siguza Is there anything I can do to help speed along a possible fix? :(

**Comment by mibby** [comment]
@Siguza Please come back.

**Comment by jordanwilliams1** [comment]
@mibby Did you get this fixed :( ? @Siguza is gone 4 ever :(

**Comment by mibby** [comment]
@jordanwilliams1 Unfortunately I have not, no. Hoping for @Siguza to return. :(
